---
title: ""
output:
  html_document:
    df_print: paged
  pdf_document: default
---

Amtrack - Forecasting passenger demand

```{r}
library(zoo)
library(forecast)
library(urca)
```


```{r}
dados_passageiros <- read.csv("C:/Users/thami/OneDrive/Desktop/Pastas Git/Amtrak/Amtrak data.csv")
```


```{r}
passageiros_ts <- ts(dados_passageiros$Ridership, start=c(1991,1), end=c(2004,3), frequency = 12)

plot(passageiros_ts, xlab="Time", ylab="Passenger", ylim=c(1300, 2300), bty="l")
```

```{r}
#test
tam_amostra_teste <- 36

#train
tam_amostra_treinamento <- length(passageiros_ts) - tam_amostra_teste

#time series
treinamento_ts <- window(passageiros_ts, start=c(1991, 1), end=c(1991,tam_amostra_treinamento))

validacao_ts <- window(passageiros_ts, start=c(1991, tam_amostra_treinamento + 1), end=c(1991,tam_amostra_treinamento+tam_amostra_teste))

```

```{r}
#Arima
Modelo_ARIMA <- auto.arima(treinamento_ts, stepwise=FALSE, approximation = FALSE)

summary(Modelo_ARIMA)

```

```{r}
#Forecast the next 12 months 
modelo_ARIMA_proj <- forecast(Modelo_ARIMA, h=tam_amostra_teste, level=0.95)


plot(modelo_ARIMA_proj, ylab="Passenger", xlab="Time", bty="l", xaxt="n", xlim=c(1991,2006.25), flty=2)

axis(1, at=seq(1991, 2006, 1), labels=format(seq(1991, 2006, 1)))

lines(Modelo_ARIMA$fitted, lwd=2, col="blue")

lines(validacao_ts)

```


```{r}
accuracy(modelo_ARIMA_proj, validacao_ts)

checkresiduals(modelo_ARIMA_proj, test="LB")

```


```{r}

#Final 
Modelo_ARIMA_final <- auto.arima(passageiros_ts, stepwise=FALSE, approximation = FALSE)

summary(Modelo_ARIMA_final)


```

```{r}
#Forecast the next 36 months
Modelo_ARIMA_final_proj <- forecast(Modelo_ARIMA_final, h=36, level=0.95)

#Train n Test
plot(Modelo_ARIMA_final_proj, xlab="Time", ylab="Passenger", ylim=c(1300, 2800), xlim=c(1991, 2007), bty="l", flty=2, main="Forecast from Polynomial regression model")
axis(1, at=seq(1991, 2007, 1), labels=format(seq(1991, 2007,1)))
lines(Modelo_ARIMA_final_proj$fitted, lwd=2, col="blue")
```


